site_name: Mof 文档
site_url: https://mofcloud.cn/docs
repo_name: mofcloud/docs
repo_url: https://github.com/mofcloud/docs

theme:
  name: material
  language: zh
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - content.code.copy

plugins:
  - glightbox
  - search
  - i18n:
      default_language: c
      languages:
        - locale: zh
          name: 简体中文
          build: true
          default: true
          nav_translations:
            Introduction: 产品介绍
            Getting started: 快速开始
            User guide: 用户指南
            Cloud Wiki: 云百科
            FinOps Wiki: FinOps 百科
            Best practice: 最佳实践
            Contact: 联系我们
            Providers: 云厂商
            AWS: AWS
            Azure: Azure
            Google Cloud: GCP
            Alibaba: 阿里云
            Huawei: 华为云
            Tencent: 腾讯云
            UCloud: UCloud
            Baidu: 百度云
            Cloudflare: Cloudflare
            Baishan: 白山云
            Agora: 声网
            Volcengine: 火山引擎
            NetEaseYidun: 网易易盾
            NetEaseYunxin: 网易云信
            ECloudValley(enterprise): ECloudValley(私有版)
            MeshCloud(enterprise): 脉时云(私有版)
            CustomCloud: 自定义云
            Smart bill: 智能账单
            Server analysis: 服务器分析
            Smart monthly bill: 智能月账单
            Monthly bill: 月账单
            Bill history: 历史账单
            Download bill: 下载账单
            Organization: 组织架构
            Sync: 数据同步
            Exchange Rate: 汇率中心
            User: 用户设置
            Tag editor: 标签管理

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - "产品介绍": "index.md"
  - "快速开始":
      - "添加云账号": "getting-started/index.md"
      - "云厂商":
          - "添加/更新基本信息": "getting-started/providers/basic.md"
          - "阿里云": "getting-started/providers/alibaba.md"
          - "腾讯云": "getting-started/providers/tencent.md"
          - "华为云": "getting-started/providers/huawei.md"
          - "火山引擎": "getting-started/providers/volcengine.md"
          - "百度云": "getting-started/providers/baidu.md"
          - "UCloud": "getting-started/providers/ucloud.md"
          - "声网": "getting-started/providers/agora.md"
          - "白山云": "getting-started/providers/baishan.md"
          - "网易云信": "getting-started/providers/yunxin.md"
          - "AWS": "getting-started/providers/aws.md"
          - "Azure": "getting-started/providers/azure.md"
          - "GCP": "getting-started/providers/gcp.md"
          - "Oracle": "getting-started/providers/oci.md"
          - "手动输入": "getting-started/providers/manual.md"
      - "数据同步": "getting-started/sync.md"
      - "用户设置": "getting-started/user-setting.md"
  - "用户指南":
      - "Smart bill":
          - "Smart monthly bill": "user-guide/bills/smart.md"
          - "Bill history": "user-guide/bills/history.md"
          - "Download bill": "user-guide/bills/download.md"
          - "Server analysis": "user-guide/bills/server.md"
      - "Organization": "user-guide/org/index.md"
      - "Sync": "user-guide/sync/index.md"
      - "Tag editor": "user-guide/tagging/index.md"
      - "Exchange Rate": "user-guide/exchange/index.md"
      - "User": "user-guide/user/index.md"
  - "Contact": "contact/index.md"

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://mofcloud.cn

copyright: Copyright &copy; 2024 mofcloud
