site_name: Mof 产品文档
site_url: https://mofcloud.cn/docs
repo_name: mofcloud/docs-cn
repo_url: https://github.com/mofcloud/docs-cn

theme:
  name: material
  language: zh
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - "产品介绍": "index.md"
  - "快速开始":
      - "添加云账号": "getting-started/index.md"
      - "智能账单":
          - "功能概览": "getting-started/smb/overview.md"
          - "云账号账单": "getting-started/smb/abill.md"
          - "多云账单": "getting-started/smb/pbill.md"
          - "组合账单": "getting-started/smb/ubill.md"
      - "成本分摊": "getting-started/showback.md"
      - "数据同步": "getting-started/sync.md"
      - "汇率中心": "getting-started/exchange.md"
      - "标签管理": "getting-started/tagging.md"
      - "消息订阅": "getting-started/notification.md"
      - "原始账单导出": "getting-started/export.md"
      - "访问权限": "getting-started/rbac.md"
      - "用户设置": "getting-started/user-setting.md"
      - "云服务商":
          - "添加/更新基本信息": "getting-started/providers/basic.md"
          - "阿里云": "getting-started/providers/alibaba.md"
          - "腾讯云": "getting-started/providers/tencent.md"
          - "华为云": "getting-started/providers/huawei.md"
          - "火山引擎": "getting-started/providers/volcengine.md"
          - "百度云": "getting-started/providers/baidu.md"
          - "UCloud": "getting-started/providers/ucloud.md"
          - "声网": "getting-started/providers/agora.md"
          - "白山云": "getting-started/providers/baishan.md"
          - "网易云信": "getting-started/providers/yunxin.md"
          - "AWS": "getting-started/providers/aws.md"
          - "Azure": "getting-started/providers/azure.md"
          - "GCP": "getting-started/providers/gcp.md"
          - "Oracle": "getting-started/providers/oci.md"
          - "Linode": "getting-started/providers/linode.md"
          - "Cloudflare": "getting-started/providers/cloudflare.md"
          - "OpenAI": "getting-started/providers/openai.md"
          - "手动输入": "getting-started/providers/manual.md"
      - "即时通讯":
          - "企业微信": "getting-started/comm/wechat.md"
          - "钉钉": "getting-started/comm/ding.md"
          - "飞书": "getting-started/comm/feishu.md"
  - "部署方式": "deployment/index.md"
extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://mofcloud.cn

copyright: Copyright &copy; 2025 mofcloud
