name: release

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

on:
  release:
    types:
      - 'published'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build, tag, and push docker image to HuaweiCloud SWR
        env:
          REPOSITORY: docs-cn
          IMAGE_TAG: ${{github.event.release.tag_name}}
        run: |
          docker login -u ap-southeast-1@JE9QOCCH2LGKIUVS3JUG -p df18aecc74630c437780924858ab3ae4fd92f13829d45beca3af9ef3234a4352 swr.ap-southeast-1.myhuaweicloud.com
          docker build -t swr.ap-southeast-1.myhuaweicloud.com/mofcloud/$REPOSITORY:$IMAGE_TAG .
          docker push swr.ap-southeast-1.myhuaweicloud.com/mofcloud/$REPOSITORY:$IMAGE_TAG

      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "## 有新镜像 Release\n
          > **代码仓库:** <font color=\"comment\">${{ github.repository }}</font> \n
          > **代码分支:** <font color=\"comment\">${{ github.ref }}</font> \n
          > **镜像地址:** <font color=\"comment\">swr.ap-southeast-1.myhuaweicloud.com/mofcloud/docs-cn:${{github.event.release.tag_name}}</font> \n"
          mentioned_list: '["lark","shengyu"]'
