name: release

on:
  release:
    types:
      - 'published'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "## 有新镜像 Release\n
          > **代码仓库:** <font color=\"comment\">${{ github.repository }}</font> \n
          > **代码分支:** <font color=\"comment\">${{ github.ref }}</font> \n
          > **文档地址:** <font color=\"comment\">https://mofcloud.cn/docs</font> \n"
          mentioned_list: '["lark","shengyu"]'
